ASSOCIATE_PARTY = "ASSOCIATE_PARTY" # User ASSOCIATE_PARTY Party
MEMBER_OF_PARTY = "MEMBER_OF_PARTY" #Elected Official MEMBER_OF_PARTY Party
VOTED_FOR = "VOTED_FOR" # User VOTED_FOR Law
VOTED_AGAINST = "VOTED_AGAINST" # User VOTED_AGAINTS Law
MEMBER_FOLLOWS = "MEMBER_FOLLOWS" # User MEMBER_FOLLW ElectedOfficial
WORK_AT = "WORK_AT"
RESIDING = "RESIDING"


ELECTED_VOTED_FOR= "ELECTED_VOTED_FOR"
ELECTED_VOTED_AGAINST = "ELECTED_VOTED_AGAINST"
ELECTED_ABSTAINED = "ELECTED_ABSTAINED"
ELECTED_MISSING = "ELECTED_MISSING"
PROPOSED_BY = "PROPOSED_BY"

TAGGED_AS = "TAGGED_AS"
TAGGED_LAW = "TAGGED_LAW"

LAW = "law"
