ASSOCIATE_PARTY = "ASSOCIATE_PARTY" # User ASSOCIATE_PARTY Party
MEMBER_OF_PARTY = "MEMBER_OF_PARTY" #Elected Official MEMBER_OF_PARTY Party
VOTED_FOR = "VOTED_FOR" # User VOTED_FOR Law
VOTED_AGAINST = "VOTED_AGAINST" # User VOTED_AGAINTS Law
MEMBER_FOLLOWS = "MEMBER_FOLLOWS" # User MEMBER_FOLLW ElectedOfficial
WORK_AT = "WORK_AT"
RESIDING = "RESIDING"


ELECTED_VOTED_FOR_FIRST = "ELECTED_VOTED_FOR_FIRST"
ELECTED_VOTED_FOR_SECOND = "ELECTED_VOTED_FOR_SECOND"
ELECTED_VOTED_FOR_THIRD = "ELECTED_VOTED_FOR_THIRD"

ELECTED_VOTED_AGAINST_FIRST = "ELECTED_VOTED_AGAINST_FIRST"
ELECTED_VOTED_AGAINST_SECOND = "ELECTED_VOTED_AGAINST_SECOND"
ELECTED_VOTED_AGAINST_THIRD = "ELECTED_VOTED_AGAINST_THIRD"

ELECTED_ABSTAINED_FIRST = "ELECTED_ABSTAINED_FIRST"
ELECTED_ABSTAINED_SECOND = "ELECTED_ABSTAINED_SECOND"
ELECTED_ABSTAINED_THIRD = "ELECTED_ABSTAINED_THIRD"

ELECTED_MISSING_FIRST = "ELECTED_MISSING_FIRST"
ELECTED_MISSING_SECOND = "ELECTED_MISSING_SECOND"
ELECTED_MISSING_THIRD = "ELECTED_MISSING_THIRD"

TAGGED_AS = "TAGGED_AS"
TAGGED_LAW = "TAGGED_LAW"
